### PR TITLE
Add support to async in communicator and controller

### LINKED ISSUE #5: Network stack restart problem
Hello Balint,

Could you please check discussion here:

https://github.com/laszlojakab/homeassistant-easycontrols/issues/46

and here:

https://github.com/home-assistant/core/issues/59170

Maybe the issue related to eazyctrl package.

Regards,
Laszlo

### PR DESCRIPTION
**Pull request by laszlojakab**
### Description
This PR adds support to communicate with the Helios device in async manner. This modifications requires to fix #5

### CODE REVIEW

**Review by baradi09 — COMMENTED** [review]
Cool, that looks very promising, thanks a lot. (I have to admit, I did not make much with async IO so far). Two questions:

- What is your judgement, is it worth to keep the original blocking versions of the `EazyCommunicator` and `EazyController` objects?
- I am somewhat worried about the async version of the `set_variable()` method. If I understand it correctly, it could happen, that the control is given back after the name of the requested variable had been sent to the server, but before the correpsonding value had been read out (which is another communication). That would lead to a complete mess, if before returning to the read, an other other event calls `set_variable()` with a different variable name. (The modbus protocol is unfortunately not state-less :disappointed: ) Would it make sense / Would it be possible to pack the two two communications into one unit with no interruption between the write and read operations?

**Comment by laszlojakab** [comment]
> What is your judgement, is it worth to keep the original blocking versions of the `EazyCommunicator` and `EazyController` objects?

It depends. If you want be compatible with the previous version you should keep the `EazyCommunicator` and `EazyController` classes. I think it is important to keep if you want to add additional supported features for example. If there is no plan for that I think you can remove `EazyCommunicator` and `EazyController` classes.

> I am somewhat worried about the async version of the set_variable() method.

Do you mean `get_variable`? Here:

https://github.com/laszlojakab/eazyctrl/blob/b4e7b160e818a40a1e44ecd4e13914f50e58e421/bin/eazyctrl#L482-L487

At `set_variable` I only see one call to communicator.

**Comment by laszlojakab** [comment]
@baradi09 ping :) Do you worry about `get_variable` or `set_variable`?

**Comment by baradi09** [comment]
Sorry, I am somewhat busy with my professional projects... :smile: 

Yes of course, you are right, I am worried about the `get_variable()`, which involves two communications, which I think, should be coupled together as an atomic operation to decrease the chance of concurrency...

**Comment by laszlojakab** [comment]
As I see the current implementation in EazyController is only working in single threaded environment (and only with a single client connected to Helios unit). This is also true for AsyncEazyController. If multiple thread wants to communicate with the same unit it could happen that you read out a value which is not belongs to your original requested variable. Using the new AsyncEazyController (without making the read to an atomic operation) the same problem could happen. So at the moment I kept the "compatibility" with the old version. If I add a static lock around `write_variable`, and `read_variable` call I could handle the in process concurrency problems. In that case there still could be a problem if someone else queries the same Helios unit at the same time. Of cource it has a very low probability. I will add the lock to the code and install it into my Home Assistant for some testing.

**Comment by laszlojakab** [comment]
Do you know what happens in the following case:

- thread A wants to read varA so thread A calls `write_variable('varA')`
- meanwhile thread B wants to write varB so thread B calls `write_variable('varB=1')`
- thread A still wants to read varA so thread A calls `read_variable()`

Will thread A get varA or `recvvarname` will be different then `varName` and it queries again? If writing also can mess up reading then the same lock object should be used in both places.

**Comment by marvin-w** [comment]
Thank you guys for handling this issue! 

Just be aware that just because your code is now async it doesn't mean that it will run in a multithreaded environment. Asyncio is inherently single threaded (async/asyncio allows concurrency within a single thread).

This said, I don't think your issue with `write_variable` and `read_variable` is really an issue. To be safe you can just use a https://docs.python.domainunion.de/3/library/asyncio-sync.html#lock on both methods.

```python
...
lock = asyncio.Lock()

async def read_variable():
   """Read var."""
   async with self.lock:
      # do logic

async def write_variable():
   """Write var."""
   async with self.lock:
      # do logic
```

**Comment by laszlojakab** [comment]
Hello @marvin-w! Thank you for your info about asyncio. The main problem here is how the Helios units handles ModBus messages. You must use the following algorithm to get a variable value:

- you must _write_ the the variable name that you want to read, example: `varA`
- you must call read_variable to get the value of previously writtern `varA` variable

To set a variable value:
- you must write the variable and the value in the same message, example `varA=1`

As I understand asyncio (just read about that how it works) I think the variable getting part could be a problem. We want to get a variable value so we send the variable name with asyncio. During the operation an other get could be started which also sends a variable name and it will ruin the getting the first variable. I added the lock to get section and I'm testing in my HA for a while but probably the same lock should be used when setting a variable (that's the quetion I have mentioned above)

**Comment by marvin-w** [comment]
In that case I'd just add the Lock here: https://github.com/laszlojakab/eazyctrl/commit/b4e7b160e818a40a1e44ecd4e13914f50e58e421#diff-e2bfd9ad7ea9aea53f654b7c64a0cfb438c298b8cb5643469c3e971833401412R477-R494

as you've already mentioned. If you still feel like you need to restrict access to the whole bus during that time maybe an additional asyncio.Lock or even an asyncio.Event might be helpful. I'd also probably encapsulate the _reader and _writer part in an additional class and add the Lock there already as that's where the message is actually sent/received and what should actually be handled.

**Comment by baradi09** [comment]
> Do you know what happens in the following case:
> 
> * thread A wants to read varA so thread A calls `write_variable('varA')`
> * meanwhile thread B wants to write varB so thread B calls `write_variable('varB=1')`
> * thread A still wants to read varA so thread A calls `read_variable()`
> 
> Will thread A get varA or `recvvarname` will be different then `varName` and it queries again? If writing also can mess up reading then the same lock object should be used in both places.

I did not find any hints in the Helios documentation. Nevertheless, experimenting with the code snippet below suggests, that injecting a variable setting between the two messages of a variable read does no harm, at least I get the right answer with my Helios.
```
#%% Import module
import eazyctrl

#%%
server = 'helios-kwl.fritz.box'

#%% Set up communicators
comm1 = eazyctrl.EazyCommunicator(server)
comm2 = eazyctrl.EazyCommunicator(server)

#%% Announce reading 'v00104' (outside temperature)
comm1.write_variable("v00104")

#%% Set 'v00102' (fan stage)
comm2.write_variable("v00102=3")

# %% Read 'v00104' (outside temp)
comm1.read_variable(6, 7)
```

**Comment by laszlojakab** [comment]
Nice, so lock only required for reading. I will update the PR soon.

**Comment by laszlojakab** [comment]
PR updated. I introduced a module level lock. It is not the perfect solution. If someone wants to read from multiple units in parallel it could block each other's communication, but probably no one use multiple Helios units. A better (but I think overcompilated) solution would be to introduce multiple locks based on the host. If necessary this could be done in a seperate PR. @baradi09: I think we could keep the old EazyController and EazyCommunicator for now and if you want you can remove it in another PR. What do you think? Can you merge the modification?

**Comment by laszlojakab** [comment]
Hi @baradi09! How is your pro carrier going? 😄 
Any updates about code review of the PR? Can you release a new package version? An other solution for HA users could be to include the modified code temporarly in the HA integration itself if you have no time for releasing new version at the moment but I would be happier if this modified code would stay in the original eazyctrl package.

**Comment by baradi09** [comment]
@laszlojakab Thanks, for sure with more success and involvement, as this private one. :wink: 

Anyway, thanks for the PR (and for your patience), I've merged it and will upload the new version to PyPI in a minute.

**Comment by laszlojakab** [comment]
@baradi09 Thank you! :)

**Pull request merged**
