### PR TITLE
Make transaction id handling more robust

### PR DESCRIPTION
**Pull request by baradi09**

### CODE REVIEW

**Comment by baradi09** [comment]
@mahadi Would you mind to test this version as well? It should be more robust, and work even in the case when more than one write/read operations are necessary during the communication. (At the moment,I can't test it myself, and it would be good to have a positive feedback before I make a release on PyPI).

**Comment by mahadi** [comment]
Sure will give it a try

**Comment by mahadi** [comment]
I tested it for > 24 h and the error did not occur again. So i guess this is fixed now.

**Comment by baradi09** [comment]
Perfect, thanks! I have created a new release with the fix.

**Pull request merged**
